FKakSila\Bundle\MainBundle\Entity\Letter:
    type: entity
    table: null
    repositoryClass: FKakSila\Bundle\MainBundle\Entity\LetterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        transcription:
            type: string
            length: '5'
        description:
            type: text
            length: null
    lifecycleCallbacks: {  }
